### ISSUE TITLE
generateTree has failed

### ISSUE THREAD

**Issue by ribagi** [CivClassic/RealisticBiomes#2]
```
 [RealisticBiomes] generateTree has failed
java.util.ConcurrentModificationException: null
        at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901) ~[?:1.8.0_131]
        at java.util.ArrayList$Itr.next(ArrayList.java:851) ~[?:1.8.0_131]
        at org.bukkit.craftbukkit.v1_12_R1.CraftWorld.generateTree(CraftWorld.java:455) ~[spigot.jar:git-Spigot-c3093ef-7e94e65]
        at com.untamedears.realisticbiomes.persist.BlockGrower.generateTree(BlockGrower.java:154) [RealisticBiomes-1.4.1.jar:?]
        at com.untamedears.realisticbiomes.RealisticBiomes.growPlant(RealisticBiomes.java:469) [RealisticBiomes-1.4.1.jar:?]
        at com.untamedears.realisticbiomes.persist.PlantChunk.innerLoad(PlantChunk.java:197) [RealisticBiomes-1.4.1.jar:?]
        at com.untamedears.realisticbiomes.persist.PlantChunk.load(PlantChunk.java:129) [RealisticBiomes-1.4.1.jar:?]
        at com.untamedears.realisticbiomes.persist.PlantManager.loadChunk(PlantManager.java:405) [RealisticBiomes-1.4.1.jar:?]
        at com.untamedears.realisticbiomes.persist.PlantManager.growChunk(PlantManager.java:491) [RealisticBiomes-1.4.1.jar:?]
        at com.untamedears.realisticbiomes.listener.GrowListener.onChunkLoad(GrowListener.java:230) [RealisticBiomes-1.4.1.jar:?]
        at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) [spigot.jar:git-Spigot-c3093ef-7e94e65]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot.jar:git-Spigot-c3093ef-7e94e65]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot.jar:git-Spigot-c3093ef-7e94e65]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot.jar:git-Spigot-c3093ef-7e94e65]
        at net.minecraft.server.v1_12_R1.Chunk.loadNearby(Chunk.java:910) [spigot.jar:git-Spigot-c3093ef-7e94e65]
        at org.bukkit.craftbukkit.v1_12_R1.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:53) [spigot.jar:git-Spigot-c3093ef-7e94e65]
        at org.bukkit.craftbukkit.v1_12_R1.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:1) [spigot.jar:git-Spigot-c3093ef-7e94e65]
        at org.bukkit.craftbukkit.v1_12_R1.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:337) [spigot.jar:git-Spigot-c3093ef-7e94e65]
        at org.bukkit.craftbukkit.v1_12_R1.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:295) [spigot.jar:git-Spigot-c3093ef-7e94e65]
        at org.bukkit.craftbukkit.v1_12_R1.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:16) [spigot.jar:git-Spigot-c3093ef-7e94e65]
        at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:137) [spigot.jar:git-Spigot-c3093ef-7e94e65]
        at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:120) [spigot.jar:git-Spigot-c3093ef-7e94e65]
        at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:116) [spigot.jar:git-Spigot-c3093ef-7e94e65]
        at net.minecraft.server.v1_12_R1.World.getChunkAt(World.java:333) [spigot.jar:git-Spigot-c3093ef-7e94e65]
        at net.minecraft.server.v1_12_R1.World.getChunkAtWorldCoords(World.java:329) [spigot.jar:git-Spigot-c3093ef-7e94e65]
        at net.minecraft.server.v1_12_R1.World.getType(World.java:810) [spigot.jar:git-Spigot-c3093ef-7e94e65]
        at net.minecraft.server.v1_12_R1.WorldGenForest.generate(SourceFile:53) [spigot.jar:git-Spigot-c3093ef-7e94e65]
        at org.bukkit.craftbukkit.v1_12_R1.CraftWorld.generateTree(CraftWorld.java:445) [spigot.jar:git-Spigot-c3093ef-7e94e65]
        at org.bukkit.craftbukkit.v1_12_R1.CraftWorld.generateTree(CraftWorld.java:451) [spigot.jar:git-Spigot-c3093ef-7e94e65]
        at com.untamedears.realisticbiomes.persist.BlockGrower.generateTree(BlockGrower.java:154) [RealisticBiomes-1.4.1.jar:?]
        at com.untamedears.realisticbiomes.RealisticBiomes.growPlant(RealisticBiomes.java:469) [RealisticBiomes-1.4.1.jar:?]
        at com.untamedears.realisticbiomes.persist.PlantChunk.innerLoad(PlantChunk.java:197) [RealisticBiomes-1.4.1.jar:?]
        at com.untamedears.realisticbiomes.persist.PlantChunk.load(PlantChunk.java:129) [RealisticBiomes-1.4.1.jar:?]
        at com.untamedears.realisticbiomes.persist.PlantManager.loadChunk(PlantManager.java:405) [RealisticBiomes-1.4.1.jar:?]
        at com.untamedears.realisticbiomes.persist.PlantManager.growChunk(PlantManager.java:491) [RealisticBiomes-1.4.1.jar:?]

        at com.untamedears.realisticbiomes.listener.GrowListener.onChunkLoad(GrowListener.java:230) [RealisticBiomes-1.4.1.jar:?]
        at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) [spigot.jar:git-Spigot-c3093ef-7e94e65]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot.jar:git-Spigot-c3093ef-7e94e65]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot.jar:git-Spigot-c3093ef-7e94e65]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot.jar:git-Spigot-c3093ef-7e94e65]
        at net.minecraft.server.v1_12_R1.Chunk.loadNearby(Chunk.java:910) [spigot.jar:git-Spigot-c3093ef-7e94e65]
        at org.bukkit.craftbukkit.v1_12_R1.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:53) [spigot.jar:git-Spigot-c3093ef-7e94e65]
        at org.bukkit.craftbukkit.v1_12_R1.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:1) [spigot.jar:git-Spigot-c3093ef-7e94e65]
        at org.bukkit.craftbukkit.v1_12_R1.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:337) [spigot.jar:git-Spigot-c3093ef-7e94e65]
        at org.bukkit.craftbukkit.v1_12_R1.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:295) [spigot.jar:git-Spigot-c3093ef-7e94e65]
        at org.bukkit.craftbukkit.v1_12_R1.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:16) [spigot.jar:git-Spigot-c3093ef-7e94e65]
        at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:137) [spigot.jar:git-Spigot-c3093ef-7e94e65]
        at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:120) [spigot.jar:git-Spigot-c3093ef-7e94e65]
        at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:116) [spigot.jar:git-Spigot-c3093ef-7e94e65]
        at org.bukkit.craftbukkit.v1_12_R1.CraftWorld.getChunkAt(CraftWorld.java:138) [spigot.jar:git-Spigot-c3093ef-7e94e65]
        at org.bukkit.craftbukkit.v1_12_R1.CraftWorld.getBlockAt(CraftWorld.java:95) [spigot.jar:git-Spigot-c3093ef-7e94e65]
        at org.bukkit.craftbukkit.v1_12_R1.CraftWorld.getBlockAt(CraftWorld.java:568) [spigot.jar:git-Spigot-c3093ef-7e94e65]
        at org.bukkit.Location.getBlock(Location.java:91) [spigot.jar:git-Spigot-c3093ef-7e94e65]
        at com.github.igotyou.FactoryMod.structures.FurnCraftChestStructure.getFurnace(FurnCraftChestStructure.java:109) [FactoryMod-2.4.2.jar:?]
        at com.github.igotyou.FactoryMod.eggs.FurnCraftChestEgg.revive(FurnCraftChestEgg.java:106) [FactoryMod-2.4.2.jar:?]
        at com.github.igotyou.FactoryMod.utility.FileHandler.loadFromFile(FileHandler.java:266) [FactoryMod-2.4.2.jar:?]
        at com.github.igotyou.FactoryMod.utility.FileHandler.load(FileHandler.java:157) [FactoryMod-2.4.2.jar:?]
        at com.github.igotyou.FactoryMod.FactoryModManager.loadFactories(FactoryModManager.java:524) [FactoryMod-2.4.2.jar:?]
        at com.github.igotyou.FactoryMod.FactoryMod.onEnable(FactoryMod.java:30) [FactoryMod-2.4.2.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) [spigot.jar:git-Spigot-c3093ef-7e94e65]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot.jar:git-Spigot-c3093ef-7e94e65]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot.jar:git-Spigot-c3093ef-7e94e65]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381) [spigot.jar:git-Spigot-c3093ef-7e94e65]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330) [spigot.jar:git-Spigot-c3093ef-7e94e65]
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422) [spigot.jar:git-Spigot-c3093ef-7e94e65]
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383) [spigot.jar:git-Spigot-c3093ef-7e94e65]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) [spigot.jar:git-Spigot-c3093ef-7e94e65]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot.jar:git-Spigot-c3093ef-7e94e65]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot.jar:git-Spigot-c3093ef-7e94e65]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]

```

**Comment by Maxopoly** [comment]
No longer relevant as plugin was rewritten
