### ISSUE TITLE
BlockGrowEvent nullpointer stacktrace

### ISSUE THREAD

**Issue by wingzero54** [CivClassic/RealisticBiomes#38]
This error is being thrown multiple times a second

[08:48:01] [Server thread/ERROR]: Could not pass event BlockGrowEvent to RealisticBiomes v2.1.1
java.lang.NullPointerException: null
        at com.untamedears.realisticbiomes.PlantLogicManager.updateGrowthTime(PlantLogicManager.java:158) ~[?:?]
        at com.untamedears.realisticbiomes.listener.PlantListener.handleGrowEvent(PlantListener.java:101) ~[?:?]
        at com.untamedears.realisticbiomes.listener.PlantListener.onBlockGrow(PlantListener.java:63) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor131.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.4.jar:git-Paper-355]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.4.jar:git-Paper-355]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.4.jar:git-Paper-355]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.4.jar:git-Paper-355]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.handleBlockGrowEvent(CraftEventFactory.java:1147) ~[patched_1.16.4.jar:git-Paper-355]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.handleBlockGrowEvent(CraftEventFactory.java:1138) ~[patched_1.16.4.jar:git-Paper-355]
        at net.minecraft.server.v1_16_R3.BlockCactus.tick(BlockCactus.java:42) ~[patched_1.16.4.jar:git-Paper-355]
        at net.minecraft.server.v1_16_R3.BlockBase$BlockData.b(BlockBase.java:569) ~[patched_1.16.4.jar:git-Paper-355]
        at net.minecraft.server.v1_16_R3.WorldServer.a(WorldServer.java:709) ~[patched_1.16.4.jar:git-Paper-355]
        at net.minecraft.server.v1_16_R3.ChunkProviderServer.lambda$tickChunks$14(ChunkProviderServer.java:847) ~[patched_1.16.4.jar:git-Paper-355]
        at net.minecraft.server.v1_16_R3.PlayerChunkMap.forEachVisibleChunk(PlayerChunkMap.java:628) ~[patched_1.16.4.jar:git-Paper-355]
        at net.minecraft.server.v1_16_R3.ChunkProviderServer.tickChunks(ChunkProviderServer.java:825) ~[patched_1.16.4.jar:git-Paper-355]
        at net.minecraft.server.v1_16_R3.ChunkProviderServer.tick(ChunkProviderServer.java:743) ~[patched_1.16.4.jar:git-Paper-355]
        at net.minecraft.server.v1_16_R3.WorldServer.doTick(WorldServer.java:460) ~[patched_1.16.4.jar:git-Paper-355]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1356) ~[patched_1.16.4.jar:git-Paper-355]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.4.jar:git-Paper-355]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1209) ~[patched_1.16.4.jar:git-Paper-355]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:997) ~[patched_1.16.4.jar:git-Paper-355]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:178) ~[patched_1.16.4.jar:git-Paper-355]
        at java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by wingzero54** [comment]
Probably related to [this config change](https://github.com/CivClassic/AnsibleSetup/commit/c50caa632bc6b818293ecece9fedbe5e9459c2ce#diff-26106ddf19d1d2cdf8cc2affcb55f5086e5ace7936e8f88258dfd90f050fce0a) which disabled persistent cactus growth to stop lag.
