### ISSUE TITLE
Exception treating other block as Ageable

### ISSUE THREAD

**Issue by Maxopoly** [CivClassic/RealisticBiomes#6]
```
[20:55:05] [Server thread/WARN]: [RealisticBiomes] Task #241837 for RealisticBiomes v2.0.1 generated an exception
java.lang.IllegalArgumentException: Can not set age for non Ageable
        at com.untamedears.realisticbiomes.growth.AgeableGrower.setStage(AgeableGrower.java:40) ~[?:?]
        at com.untamedears.realisticbiomes.growthconfig.PlantGrowthConfig.updatePlant(PlantGrowthConfig.java:291) ~[?:?]
        at com.untamedears.realisticbiomes.PlantLogicManager.initGrowthTime(PlantLogicManager.java:67) ~[?:?]
        at com.untamedears.realisticbiomes.model.RBDAO.lambda$fill$0(RBDAO.java:156) ~[?:?]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-243]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.14.4.jar:git-Paper-243]
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1171) ~[patched_1.14.4.jar:git-Paper-243]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417) ~[patched_1.14.4.jar:git-Paper-243]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1098) ~[patched_1.14.4.jar:git-Paper-243]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:925) ~[patched_1.14.4.jar:git-Paper-243]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
```

**Comment by Maxopoly** [comment]
No longer an exception thanks to https://github.com/CivClassic/RealisticBiomes/commit/7a01b12c456309414de485caf51b557aea16a8d1, but keeping this open anyway until the underlying issue is fixed

**Comment by Maxopoly** [comment]
The added logging shows `ATTACHED_PUMPKIN_STEM` as the block at fault

**Comment by Protonull** [comment]
Yeah, the block material changes when a pumpkin / melon is spawned, and that stem is no longer `Ageable` but `Directional`
